# Generated by Django 4.1 on 2022-09-01 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_profile_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 14, 41, 0, 227586, tzinfo=datetime.timezone.utc)),
        ),
    ]
