# Generated by Django 4.1 on 2022-09-01 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_profile_reg_date_chanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanel',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 18, 7, 41, 996536, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 18, 7, 41, 995173, tzinfo=datetime.timezone.utc)),
        ),
    ]
