# Generated by Django 4.1 on 2022-09-04 13:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_alter_chanel_reg_date_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanel',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 13, 51, 21, 348919, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 13, 51, 21, 351566, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 13, 51, 21, 352853, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 13, 51, 21, 350096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 13, 51, 21, 347636, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.chanel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
