# Generated by Django 4.1.1 on 2022-09-07 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_chanel_reg_date_alter_comment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='blog/profile'),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 16, 55, 26, 668863, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 16, 55, 26, 673642, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 16, 55, 26, 675738, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_pub',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 16, 55, 26, 671446, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 7, 16, 55, 26, 665507, tzinfo=datetime.timezone.utc)),
        ),
    ]
